In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [4]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [6]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [7]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [8]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [9]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [10]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0 -0.415021       NaN       NaN
1  0.190542       NaN       NaN
2 -0.037494       NaN -0.718887
3  1.912287       NaN -1.259492
4 -0.118529 -2.234715  1.484036
5 -0.867131  0.629332 -0.057038
6 -0.341766  0.406123  0.494896

In [11]:
df.dropna()

0         1         2
4 -0.118529 -2.234715  1.484036
5 -0.867131  0.629332 -0.057038
6 -0.341766  0.406123  0.494896

In [19]:
df.dropna(thresh=2)

0         1         2
2 -0.037494       NaN -0.718887
3  1.912287       NaN -1.259492
4 -0.118529 -2.234715  1.484036
5 -0.867131  0.629332 -0.057038
6 -0.341766  0.406123  0.494896

In [20]:
df.fillna(0)

0         1         2
0 -0.415021  0.000000  0.000000
1  0.190542  0.000000  0.000000
2 -0.037494  0.000000 -0.718887
3  1.912287  0.000000 -1.259492
4 -0.118529 -2.234715  1.484036
5 -0.867131  0.629332 -0.057038
6 -0.341766  0.406123  0.494896

In [21]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.415021  0.500000  0.000000
1  0.190542  0.500000  0.000000
2 -0.037494  0.500000 -0.718887
3  1.912287  0.500000 -1.259492
4 -0.118529 -2.234715  1.484036
5 -0.867131  0.629332 -0.057038
6 -0.341766  0.406123  0.494896

In [22]:
df = pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0 -0.017267  0.283794 -0.953865
1 -0.668113 -0.046935 -0.402144
2 -0.922839       NaN -1.577658
3  0.638680       NaN -1.183056
4  0.213790       NaN       NaN
5 -1.092162       NaN       NaN

In [24]:
df.ffill()

0         1         2
0 -0.017267  0.283794 -0.953865
1 -0.668113 -0.046935 -0.402144
2 -0.922839 -0.046935 -1.577658
3  0.638680 -0.046935 -1.183056
4  0.213790 -0.046935 -1.183056
5 -1.092162 -0.046935 -1.183056

In [25]:
df.ffill(limit=2)

0         1         2
0 -0.017267  0.283794 -0.953865
1 -0.668113 -0.046935 -0.402144
2 -0.922839 -0.046935 -1.577658
3  0.638680 -0.046935 -1.183056
4  0.213790       NaN -1.183056
5 -1.092162       NaN -1.183056

In [27]:
df.fillna(data.mean())

0         1         2
0 -0.017267  0.283794 -0.953865
1 -0.668113 -0.046935 -0.402144
2 -0.922839  6.500000 -1.577658
3  0.638680  6.500000 -1.183056
4  0.213790  6.500000  3.000000
5 -1.092162  6.500000  3.000000

In [28]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [31]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [32]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [33]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [34]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [35]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [36]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon", "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [37]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [38]:
def get_animal(x):
    return meat_to_animal[x]

data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [39]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [40]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [41]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [42]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [43]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [44]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [46]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [47]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [50]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [51]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [52]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [53]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [54]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [55]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [57]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [58]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, right=False, labels=group_names)

['Youth', 'Youth', 'YoungAdult', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [59]:
data = np.random.uniform(size=20)
pd.cut(data, 4, precision=2)

[(0.5, 0.71], (0.71, 0.93], (0.074, 0.29], (0.29, 0.5], (0.074, 0.29], ..., (0.5, 0.71], (0.074, 0.29], (0.29, 0.5], (0.71, 0.93], (0.074, 0.29]]
Length: 20
Categories (4, interval[float64, right]): [(0.074, 0.29] < (0.29, 0.5] < (0.5, 0.71] < (0.71, 0.93]]

In [60]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(-0.01, 0.66], (0.66, 3.23], (-0.63, -0.01], (-0.01, 0.66], (0.66, 3.23], ..., (-0.63, -0.01], (0.66, 3.23], (-0.01, 0.66], (-0.63, -0.01], (-0.01, 0.66]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.6799999999999997, -0.63] < (-0.63, -0.01] < (-0.01, 0.66] < (0.66, 3.23]]

In [61]:
quartiles.value_counts()

(-2.6799999999999997, -0.63]    250
(-0.63, -0.01]                  250
(-0.01, 0.66]                   250
(0.66, 3.23]                    250
Name: count, dtype: int64

In [62]:
pd.cut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(0.0, 0.1]     37
(0.1, 0.5]    151
(0.5, 0.9]    133
(0.9, 1.0]     23
Name: count, dtype: int64

In [63]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.027717     0.000906    -0.036091    -0.002044
std       1.004169     0.966058     1.009705     0.974222
min      -3.362311    -2.961386    -3.190943    -3.118233
25%      -0.631397    -0.659313    -0.707499    -0.654080
50%       0.009670     0.025854    -0.007799    -0.007278
75%       0.691648     0.607132     0.650603     0.678525
max       3.142570     3.458066     3.084204     2.864784

In [65]:
col = data[2]
col[col.abs() > 3]

438    3.060078
788    3.084204
897   -3.190943
Name: 2, dtype: float64

In [66]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
148 -3.362311 -1.007241 -0.432785  0.899965
198  1.617945 -0.078348  0.185360 -3.118233
311 -3.149754  1.992564 -1.279171 -1.456627
417  3.109515 -0.718962  0.119115  1.486013
438  1.015793 -0.878328  3.060078 -1.806903
714 -3.006184  0.530179 -1.033932  0.189211
788  0.688497  0.736676  3.084204  0.953228
817 -1.680141  3.458066  1.455353 -1.064260
867  3.142570  0.198453  0.361908 -1.276916
897  1.746817  0.556337 -3.190943  0.818671

In [67]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.027983     0.000448    -0.036044    -0.001925
std       1.001762     0.964525     1.008686     0.973851
min      -3.000000    -2.961386    -3.000000    -3.000000
25%      -0.631397    -0.659313    -0.707499    -0.654080
50%       0.009670     0.025854    -0.007799    -0.007278
75%       0.691648     0.607132     0.650603     0.678525
max       3.000000     3.000000     3.000000     2.864784

In [69]:
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [70]:
sampler = np.random.permutation(5)
sampler

array([3, 2, 0, 1, 4], dtype=int32)

In [71]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [72]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [73]:
column_sampler = np.random.permutation(7)
column_sampler

array([0, 1, 2, 4, 6, 3, 5], dtype=int32)

In [74]:
df.take(column_sampler, axis=1)

0   1   2   4   6   3   5
0   0   1   2   4   6   3   5
1   7   8   9  11  13  10  12
2  14  15  16  18  20  17  19
3  21  22  23  25  27  24  26
4  28  29  30  32  34  31  33

In [75]:
df.sample(n=3)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [76]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace=True)

3    6
1    7
4    4
3    6
4    4
0    5
3    6
2   -1
1    7
2   -1
dtype: int64

In [77]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [78]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [79]:
dummies = pd.get_dummies(df["key"], prefix="key")
df_with_dummies = df[["data1"]].join(dummies)
df_with_dummies

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [81]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("D:/Python/Data_analysis/data_Book/datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [84]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [85]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [86]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [87]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [88]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [89]:
s.dtype

dtype('float64')

In [90]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [91]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [92]:
s.dtype

Int64Dtype()

In [93]:
s[3]

<NA>

In [94]:
s[3] is pd.NA

True

In [95]:
s[3] is np.nan

False

In [96]:
s = pd.Series([1, 2, 3, None], dtype="Int64")
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [98]:
s = pd.Series(["one", "two", None, "three"], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [99]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [100]:
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [101]:
val = "a,b,   guido"
val.split(",")

['a', 'b', '   guido']

In [102]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [103]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [104]:
"::".join(pieces)

'a::b::guido'

In [105]:
"guido" in val

True

In [106]:
val.index(",")

1

In [107]:
val.find(":")

-1

In [108]:
val.count(",")

2

In [109]:
val.replace(",", "::")

'a::b::   guido'

In [110]:
val.replace(",", "")

'ab   guido'

In [111]:
import re
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [114]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [115]:
regex.findall(text)

['    ', '\t ', '  \t']

In [116]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [118]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [119]:
text[m.start():m.end()]

'dave@google.com'

In [122]:
print(regex.match(text))

None


In [123]:
regex.sub("REDACTED", text)

'Dave REDACTED\nSteve REDACTED\nRob REDACTED\nRyan REDACTED'

In [124]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [126]:
m = regex.match("wesm@bright.net")
m

<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [127]:
m.groups()

('wesm', 'bright', 'net')

In [129]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [130]:
regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text)

'Dave Username: dave, Domain: google, Suffix: com\nSteve Username: steve, Domain: gmail, Suffix: com\nRob Username: rob, Domain: gmail, Suffix: com\nRyan Username: ryan, Domain: yahoo, Suffix: com'

In [132]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com", "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [133]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [134]:
data_as_string_ext = data.astype("string")
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [135]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [136]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [137]:
data.str.findall(pattern, flags=re.IGNORECASE).str[0]

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [139]:
data.str.findall(pattern, flags=re.IGNORECASE).str[0].str[1]

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [140]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [141]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [142]:
values = pd.Series(["apple", "orange", "apple", "apple"] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [144]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [146]:
values.value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [147]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(["apple", "orange"])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [148]:
dim

0     apple
1    orange
dtype: object

In [149]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [150]:
fruits = ["apple", "orange", "apple", "apple"] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

In [152]:
df = pd.DataFrame({"fruits": fruits,
                   "basket_id": np.arange(N),
                   "count": rng.integers(3, 15, size=N),
                   "weight": rng.uniform(0, 4, size=N)},
                   columns=["basket_id", "fruits", "count", "weight"])
df

basket_id  fruits  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [154]:
fruit_cat = df["fruits"].astype("category")
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruits, dtype: category
Categories (2, object): ['apple', 'orange']

In [155]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [156]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [157]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [158]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [159]:
df["fruits"] = df["fruits"].astype("category")
df["fruits"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruits, dtype: category
Categories (2, object): ['apple', 'orange']

In [161]:
my_categories = pd.Categorical(["foo", "bar", "baz", "foo", "bar"])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [162]:
categories = ["foo", "bar", "baz"]
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [163]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [164]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [165]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [166]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [168]:
bins = pd.qcut(draws, 4, labels=["Q1", "Q2", "Q3", "Q4"])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [170]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [176]:
bins = pd.Series(bins, name="quartile")
results = (pd.Series(draws).groupby(bins, observed=False).agg(["count", "min", "max"]).reset_index())
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [177]:
results["quartile"]

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [178]:
N = 10_000_000
labels = pd.Series(["foo", "bar", "baz", "qux"] * (N // 4))
categories = labels.astype("category")

In [179]:
labels.memory_usage(deep=True)

520000132

In [180]:
categories.memory_usage(deep=True)

10000512

In [181]:
%time _ = labels.astype("category")

CPU times: total: 438 ms
Wall time: 469 ms


In [182]:
%timeit labels.value_counts()

388 ms ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [183]:
%timeit categories.value_counts()

43.1 ms ± 3.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [184]:
s = pd.Series(["a", "b", "c", "d"] * 2)
cat_s = s.astype("category")
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [185]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [186]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [187]:
actual_categories = ["a", "b", "c", "d", "e"]
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [188]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [189]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [190]:
cat_s3 = cat_s[cat_s.isin(["a", "b"])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [191]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [192]:
cat_s = pd.Series(["a", "b", "c", "d"] * 2, dtype="category")

In [193]:
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True